/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123nameChar125DotjsonRouteImport } from './routes/{$name}[.]json'
import { Route as RegistryDotjsonRouteImport } from './routes/registry[.]json'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UtilitiesIndexRouteImport } from './routes/utilities.index'
import { Route as ComponentsIndexRouteImport } from './routes/components.index'
import { Route as BlocksIndexRouteImport } from './routes/blocks.index'
import { Route as UtilitiesNameRouteImport } from './routes/utilities.$name'
import { Route as RChar123nameChar125DotjsonRouteImport } from './routes/r/{$name}[.]json'
import { Route as RRegistryDotjsonRouteImport } from './routes/r/registry[.]json'
import { Route as ComponentsNameRouteImport } from './routes/components.$name'
import { Route as BlocksNameRouteImport } from './routes/blocks.$name'

const Char123nameChar125DotjsonRoute =
  Char123nameChar125DotjsonRouteImport.update({
    id: '/{$name}.json',
    path: '/{$name}.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const RegistryDotjsonRoute = RegistryDotjsonRouteImport.update({
  id: '/registry.json',
  path: '/registry.json',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesIndexRoute = UtilitiesIndexRouteImport.update({
  id: '/utilities/',
  path: '/utilities/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilitiesNameRoute = UtilitiesNameRouteImport.update({
  id: '/utilities/$name',
  path: '/utilities/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RChar123nameChar125DotjsonRoute =
  RChar123nameChar125DotjsonRouteImport.update({
    id: '/r/{$name}.json',
    path: '/r/{$name}.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const RRegistryDotjsonRoute = RRegistryDotjsonRouteImport.update({
  id: '/r/registry.json',
  path: '/r/registry.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNameRoute = ComponentsNameRouteImport.update({
  id: '/components/$name',
  path: '/components/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksNameRoute = BlocksNameRouteImport.update({
  id: '/blocks/$name',
  path: '/blocks/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/{$name}.json': typeof Char123nameChar125DotjsonRoute
  '/blocks/$name': typeof BlocksNameRoute
  '/components/$name': typeof ComponentsNameRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/utilities/$name': typeof UtilitiesNameRoute
  '/blocks/': typeof BlocksIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/utilities/': typeof UtilitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/{$name}.json': typeof Char123nameChar125DotjsonRoute
  '/blocks/$name': typeof BlocksNameRoute
  '/components/$name': typeof ComponentsNameRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/utilities/$name': typeof UtilitiesNameRoute
  '/blocks': typeof BlocksIndexRoute
  '/components': typeof ComponentsIndexRoute
  '/utilities': typeof UtilitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registry.json': typeof RegistryDotjsonRoute
  '/{$name}.json': typeof Char123nameChar125DotjsonRoute
  '/blocks/$name': typeof BlocksNameRoute
  '/components/$name': typeof ComponentsNameRoute
  '/r/registry.json': typeof RRegistryDotjsonRoute
  '/r/{$name}.json': typeof RChar123nameChar125DotjsonRoute
  '/utilities/$name': typeof UtilitiesNameRoute
  '/blocks/': typeof BlocksIndexRoute
  '/components/': typeof ComponentsIndexRoute
  '/utilities/': typeof UtilitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registry.json'
    | '/{$name}.json'
    | '/blocks/$name'
    | '/components/$name'
    | '/r/registry.json'
    | '/r/{$name}.json'
    | '/utilities/$name'
    | '/blocks/'
    | '/components/'
    | '/utilities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registry.json'
    | '/{$name}.json'
    | '/blocks/$name'
    | '/components/$name'
    | '/r/registry.json'
    | '/r/{$name}.json'
    | '/utilities/$name'
    | '/blocks'
    | '/components'
    | '/utilities'
  id:
    | '__root__'
    | '/'
    | '/registry.json'
    | '/{$name}.json'
    | '/blocks/$name'
    | '/components/$name'
    | '/r/registry.json'
    | '/r/{$name}.json'
    | '/utilities/$name'
    | '/blocks/'
    | '/components/'
    | '/utilities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistryDotjsonRoute: typeof RegistryDotjsonRoute
  Char123nameChar125DotjsonRoute: typeof Char123nameChar125DotjsonRoute
  BlocksNameRoute: typeof BlocksNameRoute
  ComponentsNameRoute: typeof ComponentsNameRoute
  RRegistryDotjsonRoute: typeof RRegistryDotjsonRoute
  RChar123nameChar125DotjsonRoute: typeof RChar123nameChar125DotjsonRoute
  UtilitiesNameRoute: typeof UtilitiesNameRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  UtilitiesIndexRoute: typeof UtilitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{$name}.json': {
      id: '/{$name}.json'
      path: '/{$name}.json'
      fullPath: '/{$name}.json'
      preLoaderRoute: typeof Char123nameChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry.json': {
      id: '/registry.json'
      path: '/registry.json'
      fullPath: '/registry.json'
      preLoaderRoute: typeof RegistryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/': {
      id: '/utilities/'
      path: '/utilities'
      fullPath: '/utilities/'
      preLoaderRoute: typeof UtilitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities/$name': {
      id: '/utilities/$name'
      path: '/utilities/$name'
      fullPath: '/utilities/$name'
      preLoaderRoute: typeof UtilitiesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/{$name}.json': {
      id: '/r/{$name}.json'
      path: '/r/{$name}.json'
      fullPath: '/r/{$name}.json'
      preLoaderRoute: typeof RChar123nameChar125DotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/registry.json': {
      id: '/r/registry.json'
      path: '/r/registry.json'
      fullPath: '/r/registry.json'
      preLoaderRoute: typeof RRegistryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$name': {
      id: '/components/$name'
      path: '/components/$name'
      fullPath: '/components/$name'
      preLoaderRoute: typeof ComponentsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$name': {
      id: '/blocks/$name'
      path: '/blocks/$name'
      fullPath: '/blocks/$name'
      preLoaderRoute: typeof BlocksNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistryDotjsonRoute: RegistryDotjsonRoute,
  Char123nameChar125DotjsonRoute: Char123nameChar125DotjsonRoute,
  BlocksNameRoute: BlocksNameRoute,
  ComponentsNameRoute: ComponentsNameRoute,
  RRegistryDotjsonRoute: RRegistryDotjsonRoute,
  RChar123nameChar125DotjsonRoute: RChar123nameChar125DotjsonRoute,
  UtilitiesNameRoute: UtilitiesNameRoute,
  BlocksIndexRoute: BlocksIndexRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  UtilitiesIndexRoute: UtilitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
